// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJxjKNm3vTNQa68UrhQF4r-tlI9HCAbY',
    appId: '1:251146862934:web:32f1036faf60d6aef196f7',
    messagingSenderId: '251146862934',
    projectId: 'd-drone-d9b66',
    authDomain: 'd-drone-d9b66.firebaseapp.com',
    storageBucket: 'd-drone-d9b66.appspot.com',
    measurementId: 'G-5QD0V3QT0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8xO6hs-JWDPn--UL61fScF5-vScsZFqo',
    appId: '1:251146862934:android:538a8e79e7a4c35df196f7',
    messagingSenderId: '251146862934',
    projectId: 'd-drone-d9b66',
    storageBucket: 'd-drone-d9b66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwE8AJv8Svlwr5qtulrlw43t02O5rAdBE',
    appId: '1:251146862934:ios:a98e2a1255e88cfdf196f7',
    messagingSenderId: '251146862934',
    projectId: 'd-drone-d9b66',
    storageBucket: 'd-drone-d9b66.appspot.com',
    iosBundleId: 'com.example.ap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwE8AJv8Svlwr5qtulrlw43t02O5rAdBE',
    appId: '1:251146862934:ios:b1f087ba8e9745d7f196f7',
    messagingSenderId: '251146862934',
    projectId: 'd-drone-d9b66',
    storageBucket: 'd-drone-d9b66.appspot.com',
    iosBundleId: 'com.example.ap.RunnerTests',
  );
}
