# Generated by Django 4.2.6 on 2023-11-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idOrg', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
